m3db/m3db-operator

.travis.yml, build/ci-install-minikube.sh, build/ci-test-minikube.sh
This modifies the CI process to build a docker image locally rather than having
to push to a remote repo and pull down anew. Notably, this also makes CI a no-op
since we're making a lot of PRs related to the CI process and operator behavior. I think
once all open PRs land we re-enable the integration tests.
=> [ci] build container image locally on travis

.gitattributes, pkg/k8sops/generators.go, pkg/k8sops/generators_test.go
As of https://github.com/m3db/m3/pull/997 we have a more accurate method
of checking whether a node is bootstrapped.
=> [k8sops] move readiness probes to new script

README.md, pkg/controller/add_cluster.go, pkg/controller/controller.go, pkg/controller/update_cluster.go, pkg/util/eventer/eventer.go, pkg/util/eventer/eventer_test.go, pkg/util/eventer/options.go
Issue #26
standardize kubernetes events in terms of our operator to actually be informative to the user
Initialized events recorder package with some starter event reasons (subject to change ofc)
moved the k8.io/client-go/tools/record to the util/eventerdirectory
replaced existing c.recorder lines with the new eventer.Post....lines
removed some c.logger lines where i added the new eventer lines because the logger is passed in, this might be incorrect though so please review
re-scope the EventReasons
add eventer.Post... to wherever we see fit as we make updates to this repo
=> Pkg for K8 Events 

Makefile, README.md, pkg/controller/common_test.go, pkg/controller/controller.go, pkg/controller/controller_test.go, pkg/controller/fixtures/cluster-3-zones.yaml, pkg/controller/update_cluster.go, pkg/controller/update_cluster_test.go, pkg/m3admin/placement/options.go, pkg/m3admin/placement/options_test.go, pkg/m3admin/placement/placement.go, pkg/m3admin/placement/placement_mock.go, pkg/m3admin/placement/placement_test.go
- Support cluster instance removal w/ sanity checks.
- Implement remove operations in m3admin client.
- Define m3 placement URLs locally (remove URL has `{%s}` in it for mux
var parsing, defining locally to "freeze" paths).
=> [controller] support instance removes

.excludecoverage, Gopkg.lock, Makefile, integration/e2e/README.md, integration/e2e/basic_test.go, integration/e2e/dummy.go, integration/e2e/main_test.go, integration/harness/dummy.go, integration/harness/etcd.go, integration/harness/harness.go, integration/harness/m3admin.go, integration/harness/m3dbcluster.go, integration/harness/operator.go, integration/harness/run_suite.go, integration/manifests/cluster-1.yaml, integration/manifests/etcd.yaml, integration/manifests/operator.yaml, scripts/run_e2e_tests.sh
This adds a basic integration test for ensuring operator functionality
against a real Kubernetes cluster.
So far only basic functionality is tested: installing the operator and
creating a 3 node M3DB cluster with no persistent storage. The tests
ensure the cluster is created within a certain amount of time and that
the placement is valid.
Note that these tests currently do not run on CI, but such functionality
is planned. Eventually we'll have creds and infrastructure to create a
GKE cluster from CI on certain commits. Right now the tests have to be
run locally against a working Kubernetes cluster.
=> [tests] add e2e integration framework + tests

Gopkg.lock, Gopkg.toml, pkg/client/clientset/versioned/clientset.go, pkg/client/clientset/versioned/fake/clientset_generated.go, pkg/client/clientset/versioned/typed/m3dboperator/v1/fake/fake_m3dbcluster.go, pkg/client/informers/externalversions/factory.go, pkg/controller/common_test.go, pkg/controller/controller.go, pkg/controller/controller_test.go, pkg/controller/update_cluster.go, pkg/controller/update_cluster_test.go, pkg/k8sops/generators.go, pkg/k8sops/generators_test.go, pkg/k8sops/k8sops_mock.go, pkg/k8sops/podidentity/provider.go, pkg/k8sops/podidentity/provider_mock.go, pkg/k8sops/podidentity/provider_test.go, pkg/m3admin/client_mock.go, pkg/m3admin/namespace/client_mock.go, pkg/m3admin/placement/client_mock.go
Pulls in more recent client versions and updates usage of a
to-be-deprecated field.
Tested by running against a 1.10 and 1.11 cluster.
Had to make some changes to ensure the same status update functions work
across both versions and didn't trigger constant loop updates. Also
modified the re-enqueue logic to refresh our view of the world rather
than re-entering the loop.
=> [api] support Kubernetes 1.11

pkg/controller/update_cluster.go, pkg/controller/update_cluster_test.go, pkg/k8sops/generators.go, pkg/k8sops/generators_test.go, pkg/k8sops/statefulset.go
- Run gofmt simplify on generators_test.go, statefulset.go, and update_cluster_test.go
- Replace Version(deprecated) with Versions in GenerateCRD
- Fix superfluous err!=nil check in update_cluster.go
These changes should be harmless and non-breaking :).
=> Minor code cleanup of m3db_operator

bundle.yaml, helm/m3db-operator/templates/cluster_role.yaml
`client-go` sometimes needs to patch events in addition to creating
them.
=> [rbac] add event patch permission

Gopkg.lock, Gopkg.toml, cmd/m3db-operator/main.go, docs/api.md, pkg/apis/m3dboperator/v1alpha1/namespace.go, pkg/controller/controller.go, pkg/m3admin/client.go, pkg/m3admin/client_test.go, pkg/m3admin/namespace/namespace.go, pkg/m3admin/namespace/namespace_test.go, pkg/m3admin/namespace/presets.go
We'd previously been using `time.Duration` as the type of various
durations in the namespace options. I swear this was working a while ago
so I'm not sure if something changes with `client-go` or if I totally
missed and issue. This changes the CRD to use strings and parse the
durations separately, which should fix the issue of the string
durations failing to parse.
Also added some context to the namespace create error and include it in
an event.
=> [api] represent durations as strings

pkg/controller/add_cluster.go, pkg/controller/add_cluster_test.go, pkg/controller/update_cluster.go, pkg/controller/update_cluster_test.go
We were checking against the wrapped errors which caused the placement
and namespace controller actions to behave incorrectly.
Fixes #96
=> [controller] unwrap errors from m3admin

docs/api.md, example/m3db-cluster-per-zone-storageclass.yaml, example/m3db-cluster.yaml, pkg/apis/m3dboperator/v1alpha1/cluster.go, pkg/k8sops/generators.go, pkg/k8sops/generators_test.go, scripts/run_e2e_tests.sh
Users running Kubernetes < 1.12, in which topology-aware volume
scheduling was introduced, cannot use a single storageclass for all
their statefulsets as there is no guarantee that the PV for a pod will
be created in the zone the pod is pinned to. This can cause pods to be
stuck in an unschedulable state.
This allows users to specify a StorageClass per-statefulset (zone). This
solves the above problem as a single StorageClass can be created with
attributes to specify that PVs created with it will be in a given zone
(see
https://v1-11.docs.kubernetes.io/docs/concepts/storage/storage-classes/).
Fixes #92
=> [api] support per-isogroup storageclasses

pkg/controller/controller.go, pkg/controller/controller_test.go, pkg/controller/update_cluster.go, pkg/controller/update_cluster_test.go, pkg/k8sops/generators_test.go, pkg/k8sops/statefulset.go
We had been constructing the wrong selectors when querying children
pods if the cluster had custom labels.
=> [controller] fix incorrect label selectors

Makefile, bundle.yaml, docs/api.md, helm/m3db-operator/templates/stateful_set.yaml, pkg/apis/m3dboperator/v1alpha1/cluster.go, pkg/apis/m3dboperator/v1alpha1/zz_generated.deepcopy.go, pkg/k8sops/fixtures/testM3DBCluster.yaml, pkg/k8sops/generators.go, pkg/k8sops/generators_test.go, pkg/k8sops/statefulset.go
Allows users to specify their own pod and container-level security
contexts for all pods created by the operator's statefulsets. Also makes
the operator's pod itself a more locked down default.
=> [api] allow specifying security contexts

pkg/controller/m3admin_client.go
We added per-environment headers to support the case where a user was
changing the environment and we didn't want a race based on which nodes
got the new config first. However, this ends up adding more
complications. Let's assume that environments will always stay the same
(if using the default configmap we never change it) and make this logic
easier.
=> [m3admin] don't set per-environment header

pkg/controller/m3admin_client.go
This reverts commit 45e6abb4acc9edb6a18d04ffe449956c2d2b8b19.
We made that change under the assumption that m3coordinator would use
the environment in its config file as the default if none was set, but
it turns out it always defaults to `default_env`. Instead we'll add
warning to the documentation that users must always set their env to
`$NAMESPACE/$CLUSTER` if using a custom config.
=> [m3admin] restore per-environment header

docs/api.md, pkg/apis/m3dboperator/v1alpha1/cluster.go, pkg/apis/m3dboperator/v1alpha1/zz_generated.deepcopy.go, pkg/k8sops/fixtures/testM3DBCluster.yaml, pkg/k8sops/generators.go, pkg/k8sops/generators_test.go
Some users wish to use taints/tolerations to pin M3DB instances to
dedicated nodes, and keep other pods off of them. This allows specifying
tolerations in the cluster spec.
Note that we currently allow specifying tolerations on the cluster level
and not the `isolationgroup` level, as it seems like most common use
cases would be setting aside nodes for M3DB using a single taint rather
than a per-zone taint. If user requests for per-isogroup tolerations
arise we can reconsider.
=> [api] allow specifying pod tolerations

pkg/controller/add_cluster.go, pkg/controller/add_cluster_test.go
Now that we have a default template for configmaps that we construct for
users, we should continuously reconcile it. This will allow us to roll
out new config for M3DB over time and know that users' clusters will
pick up our changes.
This logic doesn't trigger if the user has a custom configmap.
=> [controller] continuously reconcile configmaps

docs/api.md, pkg/apis/m3dboperator/v1alpha1/cluster.go, pkg/k8sops/fixtures/testM3DBCluster.yaml, pkg/k8sops/generators_test.go, pkg/k8sops/statefulset.go
=> [api] support pod priority classes

scripts/migrate_etcd_0.2_0.3.sh
In the next release of the operator we'll be changing the default m3db
configmap, and thus how data is stored in etcd. This provides a script
that will let users migrate their data from one etcd keyspace to another
based on their cluster name.
Instructions for using the script to be included in release notes.
=> [scripts] add script for migrating etcd data

cmd/m3db-operator/main.go, pkg/controller/controller.go, pkg/controller/update_cluster.go, pkg/controller/update_cluster_test.go, pkg/m3admin/namespace/client.go, pkg/m3admin/placement/client.go
There was a bug in the instance removal logic that would continuously
try to remove the last pod in a set even if it had already been removed
from the placement. This fixes that.
=> [controller] fix pod removal when diff > 1

CHANGELOG.md, README.md, docs/Dockerfile, docs/configuration/configuring_m3db.md, docs/configuration/namespaces.md, docs/configuration/node_affinity.md, docs/getting_started/create_cluster.md, docs/index.md, mkdocs.yml, scripts/prep_changelog.sh
- Changelog entries for 0.2.0
- Docs on new features (tolerations, expanded node affinity)
=> [docs] node affinity docs; 0.2.0 release prep

scripts/migrate_etcd_0.1_0.2.sh
- remove new line char from etcd get
- remove key name from etcd get
- -i flag required on kubectl exec
- correct version numbers in comments
=> fix migration script

pkg/controller/update_cluster.go, pkg/k8sops/generators.go, pkg/k8sops/generators_test.go
CRD Status subresource became enabled by default in 1.11. It allows us
to only update the status part of a CRD rather than having to update the
entire API object, and will unblock OpenAPI validation errors we get if
sending the entire CRD.
https://v1-12.docs.kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/#status-subresource
Fixes #151
=> [api] use status subresource

docs/api.md, pkg/apis/m3dboperator/v1alpha1/cluster.go, pkg/apis/m3dboperator/v1alpha1/openapi_generated.go, pkg/controller/controller.go, pkg/controller/update_cluster.go, pkg/controller/update_cluster_test.go, pkg/k8sops/crd_test.go, pkg/k8sops/labels/labels.go
Leverage Kubernetes finalizers to block fully deleting the cluster until
we've cleaned up the data (placement + namespace) in etcd.
Fixes #44
=> [controller] clear data in etcd on cluster delete

pkg/k8sops/generators.go, pkg/k8sops/generators_test.go, pkg/k8sops/statefulset.go
Now that M3DB exposes health and bootstrapped endpoints immediately we
can leverage those rather than the crazy health check script.
=> [health] use dbnode health/bootstrap endpoints

pkg/controller/add_cluster_test.go, pkg/controller/common_test.go, pkg/controller/controller.go, pkg/controller/controller_test.go, pkg/controller/update_cluster_test.go
=> Always create missing stateful sets

docs/api.md, pkg/apis/m3dboperator/v1alpha1/cluster.go, pkg/apis/m3dboperator/v1alpha1/openapi_generated.go, pkg/apis/m3dboperator/v1alpha1/zz_generated.deepcopy.go, pkg/k8sops/annotations/annotations.go, pkg/k8sops/annotations/annotations_test.go, pkg/k8sops/generators.go, pkg/k8sops/generators_test.go, pkg/k8sops/statefulset.go
A few people are using annotations for configuring their pod monitoring, this will help them specify what annotations to add so they can monitor their instances.
=> Add ability to specify and set base annotations for operator resources

docs/api.md, pkg/apis/m3dboperator/v1alpha1/cluster.go, pkg/apis/m3dboperator/v1alpha1/openapi_generated.go, pkg/apis/m3dboperator/v1alpha1/zz_generated.deepcopy.go, pkg/k8sops/fixtures/testM3DBCluster.yaml, pkg/k8sops/generators_test.go, pkg/k8sops/statefulset.go
=> [cluster] support image pull secrets

Gopkg.lock, pkg/m3admin/client.go, pkg/m3admin/client_mock.go, pkg/m3admin/client_test.go, pkg/m3admin/jsonpb.go, pkg/m3admin/namespace/client.go, pkg/m3admin/placement/client.go
This makes sure that every call site is using the correct JSON marshal/unmarshal and adds helpers so future methods don't have to construct the marshaller themselves and just directly call the `DoHTTPJSONPBRequest` helper.
=> Add HTTP JSONPB request method to client and update callers

Gopkg.lock, pkg/controller/add_cluster.go, pkg/controller/controller.go
This is to avoid the issue we were seeing with Pod updates being rejected when deep copying then calling Update.
I also updated all other places we were doing copies then calling update to use patches (with the exception of our own CRDs since I figure we own the lifecycle and are in control of that).
These implementations follow the implementation of generating patches that the [postgres operator follows](https://github.com/CrunchyData/postgres-operator/blob/7e867ebf211b488def26dfaf10d7b2b5bbd6f5f6/kubeapi/pod.go#L108).
=> Use patch instead of update for resources not owned by operator

Makefile, pkg/k8sops/generators_test.go, pkg/k8sops/statefulset.go, tools.json
This will add SYS_RESOURCE to the security context if not set to ensure the M3DB image is able to call the `setrlimit` syscall for `RLIMIT_NOFILE` when it needs to raise the hard and soft open FDs limit to the value of `fs.nr_open` when they are not the same.
Fixes #137.
=> Add SYS_RESOURCE security context capability if not set

bundle.yaml, helm/m3db-operator/templates/cluster_role.yaml
Add `patch` permission on `pods`, according to https://github.com/m3db/m3db-operator/issues/168.
Might also need to regenerate bundle and remove `update` now that it's replaced by `patch`?
=> Add patch permission to m3db-operator CR

docs/getting_started/create_cluster.md, docs/getting_started/delete_cluster.md, mkdocs.yml
We've changed the way cluster deletion works due to the introduction of
the etcd cleanup finalizer. This updates the docs to reflect this.
=> [docs] Update instructions on cluster deletion

.buildkite/test.sh, Makefile, integration/harness/harness.go, integration/harness/m3admin.go
We might not be running them, but want to ensure the test code itself
still compiles.
=> [ci] Ensure integration tests always compile

.buildkite/hooks/pre-exit, .buildkite/pipeline.yml, Makefile, integration/harness/harness.go, integration/manifests/operator.yaml, scripts/kind-create-cluster.sh, scripts/run_e2e_tests.sh
**NOTE:** This can't progress until Uber's OSS Buildkite stack is upgraded. We seem to be hitting a Docker bug or similar issue that poisons the hosts. Does not appear to happen in other newer Buildkite stacks. Commenting out of default BK pipeline for now to allow others to still run the integration tests.
=> [ci] Run e2e integration tests in Kind

pkg/k8sops/m3db/generators_test.go, pkg/k8sops/m3db/statefulset.go
The StatefulSet template was not applying annotations to pods since it was not part of the pod template. This adds the same annotations to the pod.
=> Apply annotations to pods in created StatefulSets

go.mod, go.sum, pkg/k8sops/m3db/generators.go, pkg/k8sops/m3db/generators_test.go, pkg/k8sops/m3db/statefulset.go
Allows users to reference `${M3CLUSTER_ENVIRONMENT}` in custom
configmaps to reduce boilerplate. Also fixes a bug in container
environment creation that would previously overwrite default environment
variables.
=> [generators] Expose m3cluster env in pod spec

cmd/m3db-operator/main.go
This is to fix the issue proposed as https://github.com/m3db/m3db-operator/issues/204
In this PR,  I add one option so that it can have the operator only watch one namespace rather than all namespaces. In some big k8s environment, it slows the operator to add pod annotation and adds unnecessary high load the API server.
=> add one option able to only watch one specific namespace

pkg/k8sops/m3db/generators.go, pkg/k8sops/m3db/generators_test.go
By default Kubernetes will not generate DNS names for a pod if it's not
ready. This sets `publishNotReadyAddresses` on the M3DB service so that
we can look up pod IPs even when they're bootstrapping (and thus send
them writes to be buffered to commitlog).
=> [k8sops] Ensure dbnodes in DNS when bootstrapping

docs/api.md, pkg/apis/m3dboperator/v1alpha1/cluster.go, pkg/k8sops/m3db/generators.go, pkg/k8sops/m3db/generators_test.go
This allows the operator to startup in db-only mode (no colocated coordinator).  Uses an externally managed coordinator. Start the db with no "coordinator" section in the configmap.
Pass in the labels of the externally controlled coordinator's service endpoint.
`spec:
.
.
.
externalCoordinatorSelector:
app: coordinator
.
.
.`
The db-only cluster will boot up using the external coordinator.
=> tentative support for an external controlling coordinator

docs/api.md, pkg/apis/m3dboperator/v1alpha1/cluster.go, pkg/k8sops/annotations/annotations.go, pkg/k8sops/annotations/annotations_test.go, pkg/k8sops/m3db/generators_test.go, pkg/k8sops/m3db/statefulset.go
The general Annotations in the ClusterSpec get applied to both the Services and the Pods.  There are cases where the user wants annotation exclusively for the Pod, such as when marking a Pod to be scraped by Prometheus.  This PR puts in an ObjectMeta at the PodMetadata metav1.ClusterSpec level to facilitate specifying Pod-only Metadata.  I've only implemented Annotations.  I've added a test case for the Pod-only annotations.
=> Added initial support for PodMetaData, handling Annotations only

docs/api.md, pkg/apis/m3dboperator/v1alpha1/cluster.go, pkg/k8sops/m3db/generators.go, pkg/k8sops/m3db/generators_test.go
We plan on adding more ways of looking up an external coordinator than
just a selector. Allow the external config to be expanded later on.
=> [spec] Break ext coord into separate config

pkg/controller/update_cluster.go
The current logic causes some Statuses to get updated even if they
haven't changed. This causes an update storm, where updating the status
causes the cluster to be re-enqueued for processing and then have its
status updated again. This puts unnecessary load on the API server and
operator.
=> [controller] Don't update Status if noop

cmd/m3db-operator/main.go, pkg/controller/controller.go, pkg/controller/controller_test.go, pkg/controller/options.go
Continuously listing every pod and statefulset in large clusters can
slow down the operator control loops significantly. We know every pod
and statefulset created by an M3DBCluster will have predetermined
labels, and can only list objects from the Kubernetes API with those
labels.
=> [controller] Only list objects created by operator

docs/getting_started/installation.md
Updates Helm instructions to meet new format of commands with helm. Closes https://github.com/m3db/m3/issues/2496
=> [DOCS] Update helm install docs

go.sum, pkg/controller/controller.go, pkg/controller/controller_test.go
This commit fixes a bug in the logic of the `TestHandleUpdateClusterCreatesStatefulSets` test. The test checks that the controller creates all the `StatefulSet`'s in a new cluster. Previously, the test checked that all the expected `StatefulSet`'s were created by checking the length of the `map` that the test uses to track `StatefulSet`'s that were created:
```go
expectedMu.Lock()
created := len(expectedSetsCreated)
expectedMu.Unlock()
if created != len(test.expCreateStatefulSets) {
time.Sleep(100 * time.Millisecond)
continue
}
done = true
```
However, when the test creates `expectedSetsCreated` it also inserts into it all the `StatefulSet`'s that it expects so the previous `if` condition will always be true:
```go
expectedSetsCreated := make(map[string]bool)
for _, name := range …
```
=> [controller] Fix bug in TestHandleUpdateClusterCreatesStatefulSets

go.mod, go.sum, pkg/controller/controller.go, pkg/controller/controller_test.go, pkg/k8sops/annotations/annotations.go
This commit to the controller adds support for updating `StatefulSet`'s when their image or config map are out of date with the `ClusterSpec`. After checking that the cluster is healthy, the controller will next check if any `StatefulSet` needs to be updated, and will then perform any needed updates one by one. To ensure that the controller will only perform updates when it is safe to do so, the controller will check for an annotation that must be set by a user to indicate the controller can perform an update.
=> [controller] Add logic to update StatefulSets

pkg/controller/controller.go, pkg/k8sops/annotations/annotations.go
This commit defines the string that we look for to indicate that an annotation has been enabled (`"enabled"`) as a constant so it can be imported by other packages.
=> [controller] Create constant for annotation value indicating enabled

pkg/controller/controller.go, pkg/controller/controller_test.go
This commit updates the `updatedStatefulSet` method of the controller to ignore replicas when determining if it should update a StatefulSet. Changing the number of replicas in a cluster requires changes to the cluster's placement, which the controller already supports, so we can bypass checking the replicas in `updatedStatefulSet` to allow such changes to be processed by the controller later in the control loop.
=> [controller] Ignore replicas when checking for an update

pkg/controller/controller.go, pkg/controller/controller_test.go
This commit updates the controller to always remove the update annotation after processing a StatefulSet, even if the controller doesn't need to change the StatefulSet's spec. This will ensure that a user, after setting the annotation, can always know if the operator has processed a StatefulSet by checking if the annotation has been removed or not.
=> [controller] Always remove update annotation after processing StatefulSet

docs/getting_started/update_cluster.md, docs/index.md, mkdocs.yml
This commit adds a new docs file covering how to use the new `operator.m3db.io/update` annotation to enable the operator to perform updates.
=> [docs] Add documentation on updating a cluster

docs/api.md, go.mod, pkg/apis/m3dboperator/v1alpha1/cluster.go, pkg/apis/m3dboperator/v1alpha1/openapi_generated.go, pkg/controller/controller.go, pkg/controller/controller_test.go
This commit adds a new field, `Frozen`, to the `ClusterSpec` that, when set, will suspend the operator from making any changes to a cluster. This can be useful when troubleshooting a cluster as it can be used to ensure that the operator doesn't modify a cluster while you're investigating it.
=> Add frozen field to cluster spec that will suspend changes

docs/api.md, pkg/apis/m3dboperator/v1alpha1/cluster.go, pkg/controller/m3admin_client.go, pkg/controller/m3admin_client_test.go
We allow changing the selector that the coordinator service uses,
enabling users to control their M3DB clusters with coordinators that
live outside the cluster. This improves the ability to use
out-of-cluster coordinators, but has the limitation that the coordinator
must be in the same namespace as the cluster.
This PR extends external coordinator support to allow configuring a
static endpoint. This allows the user to manage the cluster with a
coordinator in a different namespace, i.e.
`global-coordinator.$OTHER_NS:7201`.
=> [api] Allow setting static external coordinator

go.mod, go.sum, pkg/controller/m3admin_client.go, pkg/controller/update_cluster.go, pkg/controller/update_cluster_test.go, pkg/m3admin/client.go, pkg/m3admin/client_test.go, pkg/m3admin/namespace/client.go, pkg/m3admin/namespace/client_mock.go, pkg/m3admin/namespace/client_test.go, pkg/m3admin/namespace/types.go
Add support for transitioning namespaces to a ready state after they've been created. This operates as a signal to coordinators pulling namespace information from etcd that the namespace is ready for use.
=> Add calls to /namespace/ready if supported by coordinator

pkg/controller/update_cluster_test.go
The order of the slice returned by `namespacesToReady` function is not defined which leads to randomly failing tests.
=> [controller] Fix flaky tests

docs/api.md, pkg/apis/m3dboperator/v1alpha1/cluster.go, pkg/apis/m3dboperator/v1alpha1/openapi_generated.go, pkg/apis/m3dboperator/v1alpha1/zz_generated.deepcopy.go, pkg/k8sops/m3db/generators.go, pkg/k8sops/m3db/generators_test.go
This commit adds support to the operator for adding sidecar containers to the pods that run the M3DB nodes.
=> Add support for adding sidecar containers

pkg/m3admin/health/client.go, pkg/m3admin/health/client_test.go, pkg/m3admin/health/types.go
We can't assume the server is listening on port 80
=> Add configurable port to health client

pkg/m3admin/health/client.go, pkg/m3admin/health/client_test.go
This returns a 200 instead of an error when not bootstrapped. This makes
it easier to differentiate between transient errors and not
bootstrapped.
=> Use /health endpoint for boostrapped check

docs/api.md, pkg/apis/m3dboperator/v1alpha1/cluster.go, pkg/apis/m3dboperator/v1alpha1/openapi_generated.go, pkg/k8sops/m3db/statefulset.go, pkg/k8sops/m3db/statefulset_test.go
Adds functionality to enable pod anti-affinity by matching for the component label against the `componentM3DBNode` value.  This functionality is disabled by default to prevent resource strain on k8s clusters.  This change also splits up the functionality of the `GenerateStatefulSetAffinity` function into two sub-functions handling node affinity and pod anti-affinity.
Fixes #123
=> Add support for pod anti-affinity

Dockerfile, cmd/m3db-operator/main.go, pkg/controller/controller.go, pkg/controller/controller_test.go
In debugging #268, I discovered that in all cases where we updated more
than 1 statefulset, it was because the observed generation on the set
was 1 less than the set's actual generation. This means that the
Kubernetes statefulset controller had not yet processed the update, and
that the information on `Status` that we check (ready replicas, current
replicas, etc.) was not up-to-date.
Also out of paranoia, I changed the update behavior to ensure that we
keep the old object meta fields around when we send the `Update` to
Kubernetes. I think if this isn't the case, we potentially overwrite a
set even if it had changed since we last process it.
This PR ensures that we stop processing the cluster if any of the set
statuses are not fresh, and that we use familiar conflict methods on set …
=> [controller] Ensure k8s statefulset statuses are fresh

example/etcd/etcd-kind.yaml, example/m3db-kind.yaml, integration/harness/etcd.go, integration/manifests/etcd.yaml, scripts/kind-create-cluster.sh
Also make test manifests work better out of the box with kind.
=> [ci] Update kind; fix node image

.gitignore, pkg/apis/m3dboperator/v1alpha1/cluster.go, pkg/apis/m3dboperator/v1alpha1/cluster_test.go, pkg/controller/m3admin_client.go, pkg/controller/m3admin_client_test.go, pkg/controller/update_cluster.go, pkg/controller/update_cluster_test.go, pkg/m3admin/placement/client.go, pkg/m3admin/placement/client_mock.go, pkg/m3admin/placement/client_test.go, pkg/m3admin/placement/types.go
Modifies the placement client `Add()` API to accept multiple instances.
=> [controller] Support multi instance placement add

pkg/apis/m3dboperator/v1alpha1/cluster.go, pkg/apis/m3dboperator/v1alpha1/openapi_generated.go, pkg/controller/controller.go, pkg/controller/controller_test.go, pkg/k8sops/annotations/annotations.go, pkg/k8sops/m3db/generators_test.go, pkg/k8sops/m3db/statefulset.go
This commits allows multiple nodes to be updated and deployed
at the same time within a statefulset. Opting into this behavior
requires the user to update the ClusterSpec to set OnDeleteUpdateStrategy
to true. When this is set, the operator will watch for the
operator.m3db.io/parallel-update annotation on statefulsets. When found,
the operator will attempt to update each statefulset, rolling N many
pods at a time where N is the value of the parallel-update annotation.
=> Add support for parallel node updates within a statefulset

pkg/controller/controller.go, pkg/controller/controller_test.go
=> Backwards compatibility when using the original update annoation with an OnDelete update strategy

pkg/k8sops/m3db/generators.go, pkg/k8sops/m3db/generators_test.go, pkg/k8sops/m3db/statefulset.go
We already use readiness probes to make sure dbnodes are bootstrapped
before taking various actions. Liveness probes are usually a good idea,
but in the case of the DB we'd rather a deadlocked node remain up so we
can debug vs. automatically killing it.
=> [k8sops] Remove liveness probes from DB

pkg/apis/m3dboperator/v1alpha1/cluster.go, pkg/apis/m3dboperator/v1alpha1/openapi_generated.go, pkg/k8sops/m3db/placement.go, pkg/k8sops/m3db/placement_test.go
This allows us to direct placement writes
to an etcd cluster other than the hardcoded "embedded"
zone.
=> [placement] Allow zone to be overridden

build/build-docker.sh
`git rev-parse HEAD` won't return an 8 character SHA by default, which we want for our docker tags
=> [build] Use --short in GITSHA calculation

pkg/controller/m3admin_client.go, pkg/controller/m3admin_client_test.go
Without this change, we could reuse clients without the proper zone header set, meaning etcd writes could be misdirected when cluster specs change during the duration of the operator's lifetime.
=> [m3admin-client] Incorporate zone into client cache

pkg/apis/m3dboperator/v1alpha1/cluster.go, pkg/apis/m3dboperator/v1alpha1/openapi_generated.go, pkg/controller/controller.go, pkg/controller/update_cluster.go, pkg/controller/update_cluster_test.go
Scaling down an M3DB cluster is a pretty heavy operation. All nodes in
the cluster must restream data, and it can put unnecessary pressure on a
cluster if accidentally triggered.
This PR adds a flag that allows users to ensure a cluster will not be
scaled down.
=> [api] Allow blocking cluster scale down

pkg/controller/update_cluster.go, pkg/controller/update_cluster_test.go
After discussing with Linas we agreed that scaling to 0 does not really makes sense and probably won't work. Since placement needs to be discarded.
=> prevent scaling down to 0 instances

bundle.yaml, helm/m3db-operator/templates/00_operator.m3db.io_m3dbclusters.yaml, pkg/apis/m3dboperator/v1alpha1/namespace.go
`extendedOptions` are used to store unstructured metadata. This PR
ensures the OpenAPI schema reflects that.
=> [api] schema: extendedOptions as untyped object
